# Generated by Django 5.0.1 on 2024-01-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmt_v2', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primitivetechnique',
            old_name='email',
            new_name='autorEmail',
        ),
        migrations.RenameField(
            model_name='primitivetechnique',
            old_name='className',
            new_name='primitiveClassName',
        ),
        migrations.RenameField(
            model_name='primitivetechnique',
            old_name='file',
            new_name='primitiveFile',
        ),
        migrations.RenameField(
            model_name='primitivetechnique',
            old_name='message',
            new_name='primitiveMessage',
        ),
        migrations.AddField(
            model_name='primitivetechnique',
            name='primitiveDescription',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
